version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.16-browsers
    steps:
      - checkout
      - run: |
          npm install --verbose
      - run: |
          npm start --verbose
