version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.22.12-browsers
    steps:
      - checkout
      - run: |
          npm install
      - run: |
          export NODE_OPTIONS="--max-old-space-size=4092"
          npm start
      - store_artifacts:
          path: /home/circleci/.npm/_logs
